//test code generated by GPT and then corrected

import { Stack } from './Stack.js';
import { LinkedList } from './LinkedList.js';
import { Node } from './Node.js';

function assertEqual(actual, expected, message) {
  if (actual !== expected) {
    console.error(`❌ ${message} — Expected: ${expected}, Got: ${actual}`);
  } else {
    console.log(`✅ ${message}`);
  }
}


console.log("=== Stack Tests ===");

//initialize a linked list with one node that has a value of 10
let list = new LinkedList(new Node(10)); 

// Initialize a stack from the linkedlist
const s = new Stack(list);
assertEqual(s.peek(), 10, "Initial value is on top");

// Push more values
s.push(new Node(20));
s.push(new Node(30));
assertEqual(s.peek(), 30, "Top after pushing 30");

// Pop a value
s.pop();
assertEqual(s.peek(), 20, "Top after popping 30 is");

// Pop again
s.pop();
assertEqual(s.peek(), 10, "Top after popping 20");

// Pop last value
s.pop();
assertEqual(s.peek(), null, "Top is null after popping everything");
assertEqual(s.isEmpty(), true, "Stack is empty now");